package com.thatapp.checklists.ModelClasses

import android.content.Context
import android.os.Environment
import android.util.Log
import java.io.FileOutputStream

import com.itextpdf.text.pdf.PdfPTable
import com.itextpdf.text.pdf.PdfWriter
import java.io.File
import java.lang.Exception
import java.text.SimpleDateFormat
import java.util.*
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import java.io.ByteArrayOutputStream
import java.io.IOException
import android.provider.MediaStore.Images.Media.getBitmap
import android.graphics.drawable.BitmapDrawable
import android.R
import android.graphics.drawable.Drawable
import android.support.v4.content.ContextCompat
import android.support.v4.content.res.ResourcesCompat
import com.google.common.reflect.Reflection.getPackageName
import com.itextpdf.text.*
import com.itextpdf.text.pdf.PdfPCell
import com.itextpdf.text.Paragraph
import com.itextpdf.text.Chapter
import com.itextpdf.text.Chunk
import com.itextpdf.text.FontFactory
import com.itextpdf.text.Font.BOLDITALIC
import com.itextpdf.text.Rectangle.*


class CreatePDF(val questions: ArrayList<QuestionItem>, val context: Context, val filename: String) {

    /* val storageDir = context.getFilesDir().absolutePath
     var fm = filename.replace("[", "").replace("]", "").split(".xls")
     var timeStamp = SimpleDateFormat("dd/MMM/YYYY_HH:mm:ss").format(Date())
     var fileNm = fm[0] + "_" + timeStamp + ".pdf"

     var des = storageDir + "/" + fileNm
     */


    val storageDir = context.getFilesDir()
    var fm = filename.replace("[", "").replace("]", "").split(".xls")
    var timeStamp = SimpleDateFormat("dd-MM-yyyy_HH:mm").format(Date())
    var fileNm = fm[0] + ":" + timeStamp + ".pdf"
    val filep = File(storageDir.getAbsolutePath() + File.separator + "generated" + File.separator + "awasrishabh")

    var des = filep.absolutePath + "/" + fileNm


    val document = Document()

    fun startPDFCreation() {

        var t = filep.mkdirs()
        Log.e("sss", " " + t)

        try {
            PdfWriter.getInstance(document, FileOutputStream(des))
        } catch (ex: Exception) {
            Log.e("eee", ex.toString())
        }
        document.pageSize = PageSize.A4
        document.isMarginMirroring = true
        document.setMargins(5f, 5f, 5f, 5f)

        document.open()

        var timeStamp = SimpleDateFormat("dd-MM-yyyy_HH:mm").format(Date())

        val paragraph1 = Paragraph("CheckList App")
        val paragraph2 = Paragraph("Generated By Rishabh Awasthi")
        val paragraph3 = Paragraph("Date Time : " + timeStamp)
        document.add(paragraph1)
        document.add(paragraph2)
        document.add(paragraph3)

        var table = PdfPTable(5)
        /*  table.setHorizontalAlignment(Element.ALIGN_RIGHT);
          // table.setWidthPercentage(30f)
          var white = Font()
          white.setColor(BaseColor.WHITE)

  //        var cell = PdfPCell(Phrase(" Outcome ", white))
  //        cell.setBackgroundColor(BaseColor.BLACK);
  //        cell.setBorderColor(BaseColor.GRAY);
  //        cell.setBorderWidth(2f);
  //        table.addCell(cell);
  */


        table = PdfPTable(3)
        table.horizontalAlignment = Element.ALIGN_RIGHT
//       table.totalWidth=45f
        table.widthPercentage = 23f
        table.setWidths(floatArrayOf(1f, 1f, 1f))

        var cellTwo = PdfPCell(Phrase("Yes"))
        cellTwo.colspan = 1
        table.addCell(cellTwo)

        cellTwo = PdfPCell(Phrase("No"))
        cellTwo.colspan = 1
        table.addCell(cellTwo)

        cellTwo = PdfPCell(Phrase("NA"))
        cellTwo.colspan = 1
        table.addCell(cellTwo)
        document.add(table)

        table = PdfPTable(5)

        table.horizontalAlignment = Element.ALIGN_LEFT

        table.widthPercentage = 100f
        table.setWidths(floatArrayOf(0.4f, 2.6f, 0.3f, 0.3f, 0.3f))
        // table.isLockedWidth = true
        for (aw in questions) {
            val ques: QuestionItem = aw
            if (ques.strHeading.length > 3) {

                var cell = PdfPCell(Phrase(ques.serialNo))
                table.addCell(cell)
                cell = PdfPCell(Phrase(ques.strHeading))

                cell.colspan = 4
                table.addCell(cell)

                cell = PdfPCell(Phrase(" "))
                //table.addCell(cell)
                //  table.addCell(cell)

            } else {
                // table = PdfPTable(3)

                var cell = PdfPCell(Phrase(ques.serialNo))
                cell.colspan = 1
                table.addCell(cell)


                cell = PdfPCell(Phrase(ques.strQuestion))
                cell.colspan = 1
                table.addCell(cell)


//            table.addCell(ques.answer + " ")
                var d: Drawable? = null
                try {
                    //  if (ques.answer.equals("YES", true)) {
                    d = ContextCompat.getDrawable(context, com.thatapp.checklists.R.drawable.ic_yes)
                    /* } else if (ques.answer.equals("NO", true)) {
                         d = ContextCompat.getDrawable(context, com.thatapp.checklists.R.drawable.multiply)
                     } else if (ques.answer.equals("--", true)) {
                         d = ContextCompat.getDrawable(context, com.thatapp.checklists.R.drawable.blank)
                     }
 */
                    val bitDw = d as BitmapDrawable
                    val bmp = bitDw.bitmap
                    val stream = ByteArrayOutputStream()
                    bmp.compress(Bitmap.CompressFormat.PNG, 100, stream)
                    val image = Image.getInstance(stream.toByteArray())

                    cell = PdfPCell(image)
                    cell.colspan = 1
                    cell.rowspan = 1
                    cell.setPadding(10f)
                    cell.fixedHeight = 30f

                    cell.setUseAscender(true)
                    cell.setUseDescender(true)
                    cell.horizontalAlignment = Element.ALIGN_CENTER
                    cell.verticalAlignment = Element.ALIGN_CENTER

                    if (ques.answer.equals("YES", true)) {
                        table.addCell(cell)
                        table.addCell("")
                        table.addCell("")
                    } else if (ques.answer.equals("NO", true)) {

                        table.addCell("")
                        table.addCell(cell)
                        table.addCell("")

                    } else if (ques.answer.equals("--", true)) {

                        table.addCell("")
                        table.addCell("")
                        table.addCell(cell)
                    }


                } catch (ex: Exception) {
                    Log.e("exxx", "111   " + ex.toString())
                }

            }

        }

        var cell = PdfPCell(Phrase("Additional Notes \n" + "1. Get Keys \n" + "2. Lock gates \n" + "3. Do something "))
        cell.colspan = 5
        cell.setPadding(5f)

        table.addCell(cell)


        var table1 = PdfPTable(4)
        table1.setWidths(floatArrayOf(2f, 2f, 2f, 3f))

        var cell1 = PdfPCell(Phrase("Operator Name \n"))
        cell1.colspan = 1
        cell1.rowspan = 2
        cell1.setPadding(5f)
        cell1.horizontalAlignment = Element.ALIGN_CENTER

        table1.addCell(cell1)

        cell1 = PdfPCell(Phrase("Vicky Singh"))
        cell1.colspan = 1
        cell1.rowspan = 2
        cell1.setPadding(5f)
        cell1.horizontalAlignment = Element.ALIGN_CENTER
        table1.addCell(cell1)

        cell1 = PdfPCell(Phrase("Signature"))
        cell1.colspan = 1
        cell1.rowspan = 2
        cell1.horizontalAlignment = Element.ALIGN_CENTER
        cell1.setPadding(5f)
        table1.addCell(cell1)
        cell1 = PdfPCell(Phrase("#"))
        cell1.colspan = 1
        cell1.rowspan = 2
        cell1.horizontalAlignment = Element.ALIGN_CENTER
        cell1.setPadding(5f)

        table1.addCell(cell1)

//        table.addCell( PdfPTable(table1))


        cell = PdfPCell(table1)
        cell.colspan = 5
        cell.rowspan = 2
        cell.setPadding(5f)
        cell.horizontalAlignment = Element.ALIGN_CENTER
        table.addCell(cell)
/*
        cell = PdfPCell(Phrase("Additional Notes \n" + "1. Get Keys \n" + "2. Lock gates \n" + "3. Do something "))
        cell.colspan = 5
        table.addCell(cell)
*/


        var table2 = PdfPTable(4)
        table2.setWidths(floatArrayOf(2f, 2f, 2f, 3f))
        cell = PdfPCell(Phrase("Work Order Number"))
        cell.colspan = 1
        cell.rowspan = 2
        cell.setPadding(5f)
        cell.horizontalAlignment = Element.ALIGN_CENTER
        table2.addCell(cell)

        cell = PdfPCell(Phrase("7878"))
        cell.colspan = 1
        cell.rowspan = 2
        cell.horizontalAlignment = Element.ALIGN_CENTER
        table2.addCell(cell)

        cell = PdfPCell(Phrase("Date"))
        cell.colspan = 1
        cell.rowspan = 2
        table2.addCell(cell)

        cell = PdfPCell(Phrase("13/12/18"))
        cell.colspan = 1
        cell.rowspan = 2
        cell.horizontalAlignment = Element.ALIGN_CENTER
        table2.addCell(cell)

//        table.addCell(PdfPCell(table2))

        cell = PdfPCell(table2)
        cell.colspan = 5
        cell.rowspan = 2
        cell.setPadding(5f)
        cell.horizontalAlignment = Element.ALIGN_CENTER
        table.addCell(cell)
        try {
            document.add(table)
        } catch (e: Exception) {
            Log.e("answer ", e.toString())
        }
        document.close()
        Log.e("answer ", "closed")
    }

}